### ISSUE TITLE
Correct definition of a symbol array

### ISSUE THREAD

**Issue by biphy** [YangLab-um/BiologicalOscillations.jl#38]
Newer versions of `ModelingToolkit.jl` (tested with v.8.70.0) distinguish the following two definitions of symbol arrays:
```julia
julia> @variables X[1:3]
1-element Vector{Symbolics.Arr{Num, 1}}:
 X[1:3]

julia> X[1]
X[1]
```
and
```julia
julia> @variables X[collect(1:3)]
1-element Vector{Symbolics.Arr{Num, 1}}:
 X[[1, 2, 3]]

julia> X[1]
ERROR: MethodError: no method matching CartesianIndices(::Tuple{Vector{Int64}})
```

`protein_interaction_network` and `gene_regulatory_network` currently use the latter way to define `species`, which leads to errors while indexing symbols with newer versions of `ModelingToolkits.jl`. For later releases, the following blocks should be corrected.

```julia
# protein_interaction_network.jl
@species (X(t))[collect(1:N)]

# gene_regulatory_network.jl
@species (m(t))[collect(1:N)]
@species (X(t))[collect(1:N)]
```

This issue might be related to the CI failure.

**Comment by ftavella** [comment]
NICE! I've been looking at it and had a note to check the same thing you're describing here. This is great and will probably solve the CI issue.
